name: Build React on S3
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: npm install
        working-directory: ./recommend-music
        
      - name: Build
        run: npm run build  # React ビルド
        working-directory: ./recommend-music

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # S3のbucket-for-deploying-react-projectバケットにデプロイ
          echo Copy S3...
          aws s3 sync ./recommend-musicbuild s3://spotify-app-react-static --region ap-northeast-1
          echo Delete Cloudfront cache...
          aws cloudfront create-invalidation --distribution-id E3OZWXUBSIJ95K --paths "/index.html"
          echo Success!
